# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-tE9fxAFlgotqwMK1X_pOIcs7UBUjcOW
"""

!pip install -q accelerate peft bitsandbytes transformers trl

!pip install datasets pandas matplotlib seaborn wordcloud transformers

from datasets import load_dataset
dataset = load_dataset("gamino/wiki_medical_terms")
print(dataset)

import pandas as pd
df = pd.DataFrame(dataset["train"])
df.head()

df = df.dropna()



import re
import string

def preprocess_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r"\[.*?\]", "", text)  # Remove references like [1], [2]
    text = re.sub(f"[{re.escape(string.punctuation)}]", "", text)  # Remove punctuation
    text = re.sub(r"\s+", " ", text).strip()  # Remove extra spaces
    return text

df["cleaned_text"] = df["page_text"].apply(preprocess_text)



df.to_csv("cleaned_text.csv", index=False)



import matplotlib.pyplot as plt
import seaborn as sns

df["word_count"] = df["cleaned_text"].apply(lambda x: len(x.split()))
sns.histplot(df["word_count"], bins=50, kde=True)
plt.title("Word Count Distribution")
plt.xlabel("Word Count")
plt.ylabel("Frequency")
plt.show()

from wordcloud import WordCloud
text_corpus = " ".join(df["cleaned_text"])
wordcloud = WordCloud(width=800, height=400, background_color="white").generate(text_corpus)
plt.figure(figsize=(10,5))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Most Common Words in Medical Dataset")
plt.show()

from collections import Counter

word_freq = Counter(" ".join(df["cleaned_text"]).split())
common_words = pd.DataFrame(word_freq.most_common(20), columns=["Word", "Frequency"])

plt.figure(figsize=(10, 5))
sns.barplot(x="Word", y="Frequency", data=common_words)
plt.xticks(rotation=45)
plt.title("Top 20 Most Frequent Words")
plt.show()

import torch

print(torch.cuda.is_available())
print(torch.version.cuda)
print(torch.cuda.get_device_name(0))

!pip uninstall bitsandbytes -y
!pip install bitsandbytes --no-cache-dir

!export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
!export PATH=/usr/local/cuda/bin:$PATH

print(torch.__version__)

!pip install transformers peft trl bitsandbytes

!huggingface-cli login

from datasets import load_dataset

dataset = load_dataset("gamino/wiki_medical_terms")

dataset = dataset['train'].shuffle(seed=42).select(range(1000))

def transform_conversation(example):
    conversation_text = example['page_text']
    segments = conversation_text.split('###')

    reformatted_segments = []

    for i in range(1, len(segments) - 1, 2):
        human_text = segments[i].strip().replace('Human:', '').strip()

        if i + 1 < len(segments):
            assistant_text = segments[i+1].strip().replace('Assistant:', '').strip()
            reformatted_segments.append(f'<s>[INST] {human_text} [/INST] {assistant_text} </s>')
        else:
            reformatted_segments.append(f'<s>[INST] {human_text} [/INST] </s>')

    return {'text': ''.join(reformatted_segments)}

transformed_dataset = dataset.map(transform_conversation)

# Cell 12: Define model and training parameters for QLoRA fine-tuning
model_name = "meta-llama/Llama-3.2-1B"
new_model = "Llama-3.2-1B-chat-finetune"

lora_r = 64
lora_alpha = 16
lora_dropout = 0.1

use_4bit = True
bnb_4bit_compute_dtype = "float16"
bnb_4bit_quant_type = "nf4"
use_nested_quant = False

output_dir = "./results"
num_train_epochs = 10
fp16 = False
bf16 = False
per_device_train_batch_size = 4
per_device_eval_batch_size = 4
gradient_accumulation_steps = 1
gradient_checkpointing = True
max_grad_norm = 0.3
learning_rate = 2e-4
weight_decay = 0.001
optim = "paged_adamw_32bit"
lr_scheduler_type = "cosine"
max_steps = -1
warmup_ratio = 0.03
group_by_length = True
save_steps = 0
logging_steps = 25

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

max_seq_length = 512

def tokenize(example):
    return tokenizer(
        example["page_text"],
        padding="max_length",
        truncation=True,
        max_length=max_seq_length,
    )

tokenized_dataset = dataset.map(tokenize, batched=True)

from transformers import AutoConfig, AutoModelForCausalLM, BitsAndBytesConfig, TrainingArguments
from peft import LoraConfig
from trl import SFTTrainer

compute_dtype=torch.float16

bnb_config=BitsAndBytesConfig(
    load_in_4bit=use_4bit,
    bnb_4bit_quant_type=bnb_4bit_quant_type,
    bnb_4bit_compute_dtype=compute_dtype,
    bnb_4bit_use_double_quant=use_nested_quant,
)

config=AutoConfig.from_pretrained(model_name)


model=AutoModelForCausalLM.from_pretrained(
    model_name,
    config=config,
    quantization_config=bnb_config,

)

peft_config=LoraConfig(
    lora_alpha=lora_alpha,
    lora_dropout=lora_dropout,
    r=lora_r,
)

training_arguments=TrainingArguments(
    output_dir=output_dir,
    num_train_epochs=num_train_epochs,
    per_device_train_batch_size=per_device_train_batch_size,
)

trainer=SFTTrainer(
    model=model,
    train_dataset=tokenized_dataset,
    peft_config=peft_config,
    args=training_arguments,
)

trainer.train()
trainer.model.save_pretrained(new_model)
tokenizer.save_pretrained(new_model)

!zip -r Llama-3.2-1B-chat-finetune.zip Llama-3.2-1B-chat-finetune

from google.colab import files
files.download("Llama-3.2-1B-chat-finetune.zip")